### ISSUE TITLE
Cannot Present Quovo Connect ViewController

### ISSUE THREAD

**Issue by normand1** [quovo/connect-ios#1]
Hi, I'm working on integrating the Quovo connect SDK into my app. After running `quovoConnect.launch(...)` I get an error:

```Warning: Attempt to present <QuovoConnectSDK.QuovoConnectSDKController: 0x7f919aa9a730> on <UINavigationController: 0x7f9198813400> whose view is not in the window hierarchy!```

This is hard for me to debug as I'm not sure what the `.launch(...)` method is doing, but it does appear to be looking for a navigation controller / view controller on which to present and not finding the correct one. Is it possible to modify this call to allow me to pass in the navigation controller / view controller on which I'd like to present? If any other possible solutions please let me know. Thanks!

**Comment by lukeguild** [comment]
Hi @normand1,
Sorry for the delayed response. We've added an optional parameter to specify a parent viewController in ef51bd8.

Thanks for the feedback!

**Comment by normand1** [comment]
@lukeguild Awesome, no worries, thank you very much. I'll check it out now.
