### ISSUE TITLE
Sample App Cannot build with Swift 4.1

### ISSUE THREAD

**Issue by mylegfeelsfunny** [quovo/connect-ios#2]
We are trying to get your example application working. But it appears it does not work with the latest Xcode release. 

````
Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1: /connect-ios-0.3.0/QuovoConnectTestProject/../QuovoConnectSDK.framework/Modules/QuovoConnectSDK.swiftmodule/x86_64.swiftmodule
````

**Comment by alexeymetelkinpro** [comment]
+1

**Comment by alexeymetelkinpro** [comment]
you may try to use different swift toolchain, download release 4.0.3 from swift.org

**Comment by stephensilber** [comment]
@alexeyhippie @mylegfeelsfunny Probably easiest to just use Swift 4.0 with Xcode 9.2 for now until they support Swift 4.1

**Comment by alexeymetelkinpro** [comment]
@stephensilber You meant 4.0.3? I tried that too and got another issue: https://github.com/quovo/connect-ios/issues/3
