### ISSUE TITLE
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler

### ISSUE THREAD

**Issue by ab-lfeng** [quovo/connect-ios#21]
Please update the framework for compatibility on Xcode 11.2. 

Based on the post below, a flag (BUILD_LIBRARY_FOR_DISTRIBUTION = YES) needs to be set to ensure forward compatibility. 

https://stackoverflow.com/questions/58654714/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler

**Comment by jkiley129** [comment]
This would be a huge help. I try to keep my project updated on the latest version of Swift and the current way the framework is developed makes that really hard. Sounds like this would solve that issue, so please take a look into this Quovo!

**Comment by jPaolantonio** [comment]
Is there a timeline for this update?
