### ISSUE TITLE
Will not compile on Swift 5.3 on Xcode 12

### ISSUE THREAD

**Issue by amyslies** [quovo/connect-ios#29]
Please enable [library evolution support](https://swift.org/blog/library-evolution/#enabling-library-evolution-support) and distributing as an xcframework

**Comment by mseijas** [comment]
+1 - we're currently blocked by this. any idea when you might be able to deliver an update for this?

**Comment by jkiley129** [comment]
+1 - Please update for this. Blocking development workflow

**Comment by carino-quovo** [comment]
New release (v1.1.14) is out that should resolve this issue.
