### ISSUE TITLE
Version 1.1.12 creates multiple build errors when running on device or building for App Store deployment

### ISSUE THREAD

**Issue by jkiley129** [quovo/connect-ios#33]
<img width="1354" alt="Screen Shot 2020-09-28 at 1 52 44 PM" src="https://user-images.githubusercontent.com/13155964/94468095-e5aae500-0191-11eb-827d-7c687d89a264.png">

**Comment by wleofeng** [comment]
Same issue here. Unable to run on device. Xcode 12. Quovo Connect version 1.1.12

**Comment by jkiley129** [comment]
This is still horribly broken and preventing my team's ability to release. Is there any news on a fix?

**Comment by carino-quovo** [comment]
apologies for the delay.  we are currently testing a release that fixes these issues, and expect it to be released via cocoa pods early next week.

**Comment by carino-quovo** [comment]
New release (v1.1.14) is out that should resolve this issue.
