### ISSUE TITLE
No callback responses for events `onOpen` and `onLoad`

### ISSUE THREAD

**Issue by marquavious** [quovo/connect-ios#5]
There are no callback responses for events `onOpen` and `onLoad`.
Here are the steps to reproduce: 

> 1. Download the latest test project
> 1. Launch Quovo SDK
> 2. Click on an institution 
> 3. Fill in the username and password fields with random letters
> 4. Click the connect button
> 5. Close the view
> 

Here is the console output:

```
add
{
    connection =     {
        id = 6451547;
        institution = 1342;
        user = 4957822;
    };
    timeStamp = 1530910732289;
}
sync
{
    connection =     {
        id = 6451547;
        institution = 1342;
        user = 4957822;
    };
    sync =     {
        authenticated = 0;
        connection = 6451547;
        status = login;
    };
    timeStamp = 1530910735463;
}
close
{
}
```

Events `onOpen` and `onLoad` where never called.

**Comment by Qyiwang** [comment]
Hi,

Can you please provide the code passed to the SDK to subscribe to the event?

Thank you,
