### ISSUE TITLE
Connect Ignores Safe Area on iPhone X

### ISSUE THREAD

**Issue by kurt-schaefer** [quovo/connect-ios#6]
![connecttoolbar](https://user-images.githubusercontent.com/419806/42775780-1ae7af64-88ea-11e8-95dc-bbf5a8b8fd13.jpg)

If I do a:
quovoConnect.launch(token:)

The modally presented view controller does not respect the Safe Area at the top of the screen, so on the iPhone X the close button gets squished against the status bar and becomes very hard to tap because it looses most of its tap-able area.  (See included image)

**Comment by IhsanBKabir** [comment]
Thanks for the feedback, @kurt-schaefer. 

If you reach out to your contacts at Quovo, they can work with you on this.
