### ISSUE TITLE
Libertarian

### ISSUE THREAD

**Issue by superbowl0** [quovo/connect-ios#7]
Having issues with the connecting my accou ts to my name and the deposits without established online info and the yahoo finance part saying i never bought shares in that instrument.

**Comment by superbowl0** [comment]
Ok

**Comment by IhsanBKabir** [comment]
Hi @superbowl0 - if you reach out to your contacts at Quovo, they should be able to assist you with this.

**Comment by lukeguild-quovo** [comment]
This repository is specifically for issues related to the iOS SDK for Connect. If you have problems with the Connect application itself or need assistance with connecting accounts you can do as @IhsanBKabir suggested and reach out to someone at Quovo directly. 

If something relevant to the Connect iOS SDK arises i'll open this back up.
